dist: trusty

os: linux
language: python
python:
    - "2.7"
env:
    - CKANVERSION=master
    - CKANVERSION=2.6
    - CKANVERSION=2.7
    - CKANVERSION=2.8

install:
    - bash bin/travis-build.bash
services:
    - redis
    - postgresql
script: bash bin/travis-run.bash
before_install:
    - pip install codecov
after_success:
    - codecov
